name: Check MSRV
on:
  push:
    branches:
      - master
    paths:
      - "**.rs"
      - "**/Cargo.toml"
  pull_request:
    branches:
      - master
    paths:
      - "**.rs"
      - "**/Cargo.toml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-min-rust-version:
    # PowerShell core is available on all platforms and can be used to unify scripts
    defaults:
      run:
        shell: pwsh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-msrv

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Check if extendr can be built
        run: cargo build --manifest-path ./extendr-api/Cargo.toml

      - name: Verify minimum rust version
        run: |
          . ./ci-cargo.ps1
          ci-cargo msrv verify --log-level debug --manifest-path ./extendr-api/Cargo.toml --output-format json -ActionName "Verify Rust MSRV"
          # ci-cargo msrv --path extendr-api/ verify -ActionName "Verify Rust MSRV"
