name: Check MSRV
on:
  push:
    branches:
      - master
    paths:
      - "**.rs"
      - "**/Cargo.toml"
  pull_request:
    branches:
      - master
    paths:
      - "**.rs"
      - "**/Cargo.toml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-min-rust-version:
    defaults:
      run:
        shell: pwsh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-msrv

      # Default R installation has been removed from OS image starting with 24.04
      # https://github.com/actions/runner-images/issues/10636
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Verify minimum rust version
        run: |
          . ./ci-cargo.ps1
          ci-cargo msrv --path extendr-api/ verify -ActionName "Verify Rust MSRV"
